const mongoose = require('mongoose');

const authoritySchema = new mongoose.Schema({
  name:         { type: String, required: true, trim: true },
  department:   { type: String, trim: true, default: '' },
  district:     { type: String, trim: true, default: '' },
  categories:   [{ type: String }],
  contactEmail: { type: String, trim: true, default: '' },
  contactPhone: { type: String, trim: true, default: '' },

  // 'admin'  — added by hand through User Management / Authorities page
  // 'ai'     — auto-generated by the rule-based area suggester
  // 'seed'   — shipped with the app so Assign always has options
  source:     { type: String, enum: ['admin', 'ai', 'seed'], default: 'admin' },
  createdBy:  { type: mongoose.Schema.Types.ObjectId, ref: 'User' },

  ratingAvg:   { type: Number, default: 0 },
  ratingCount: { type: Number, default: 0 },
}, { timestamps: true });

authoritySchema.index({ district: 1 });
authoritySchema.index({ name: 1, district: 1 }, { unique: true });

module.exports = mongoose.model('Authority', authoritySchema);